import Head from 'next/head'
import Bio from '../../components/v.1/Bio'
import Contact from '../../components/v.1/Contact'
import Header from '../../components/v.1/Header'
import Profile from '../../components/v.1/Profile'
import Skills from '../../components/v.1/Skills'
import Works from '../../components/v.1/Works'

export default function Home() {
  return (
    <div className=" bg-gray-100 dark:bg-slate-900">
      <Head>
        <title>DevWithEasy Fullstack Javascript Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="index">
        <Header/>
        <Profile/>
        <Bio/>
        <Skills/>
        <Works/>
        <Contact/>
      </main>
    </div>
  )
}